### ISSUE TITLE
How to Self-Compile?

### ISSUE THREAD

**Issue by cravend** [oscartbeaumont/netlify-dynamic-dns#10]
Hey!

I am trying to install this on a Synology NAS which uses a 32-bit ARM chipset. Any hints on how to compile this myself? I've never worked with Go before.

Thanks!

**Comment by oscartbeaumont** [comment]
You can use the following commands
```bash
git clone https://github.com/oscartbeaumont/netlify-dynamic-dns.git
cd netlify-dynamic-dns
GOOS=linux GOARCH=arm go build -o nddns_Linux ./cmd
```
You may need to tweak the `GOOS` and `GOARCH` for your device but these are defined by the Go compiler so you can research them online. I have set them to a value I think will work for your use-case but I have not tested.

**Comment by cravend** [comment]
<img width="787" alt="Screen Shot 2020-12-31 at 2 20 38 AM" src="https://user-images.githubusercontent.com/7117993/103399454-3b838600-4b0f-11eb-91c1-115eaab27f3a.png">
That worked for me, but now I'm getting an error about ipv6 when I try to run the command.

**Comment by oscartbeaumont** [comment]
Your device does not have IPv6 connectivity to the Internet which causes this issue. You can disable IPv6 by using `-ipv6=false` or you should lookup online how to get IPv6 working on your synology assuming your internet connection has support for it.

**Comment by cravend** [comment]
Got it, I didn’t realize ipv6 was on by default. Thank you!
