### ISSUE TITLE
No binary in releases where stated in the README.

### ISSUE THREAD

**Issue by gaetawoo** [oscartbeaumont/netlify-dynamic-dns#2]
There is no binary in the release view.

**Comment by oscartbeaumont** [comment]
I am current just cleaning the code base and once I finish that I will added an automatic build system to release the binary. Hopefully that will be finish in the next week.

**Comment by gaetawoo** [comment]
The idea of this is to basically make a netlify domain act as a ddns right? 

Also, with the program repeat at the specified time on its own or would it need to be run via a cron job?

**Comment by oscartbeaumont** [comment]
Yes it does act as a DDNS. I use it for my home server. It uses a Go Lang
time.Sleep to repeat the update at a set interval (you can change it if you
want).

**Comment by gaetawoo** [comment]
Brilliant. Exactly what I've been thinking about. And since the ssl certs are free and automatic on netlify, then you can use https on it?

**Comment by oscartbeaumont** [comment]
I think you are mistaken, the HTTPS certs handle by Netlify are only if you
website is hosted with them, they will not apply for your home server setup
even when using their DNS. Have a look into Caddy server it will handle the
HTTPS certs for you and it uses Let's Encrypt the same provider Netlify
use. If you have any question about this just send me an email and I can
help.

**Comment by gaetawoo** [comment]
I'll check it out thank you!

**Comment by oscartbeaumont** [comment]
This is now fixed. I completely rewrote the code cause it was really poor coding and added Travis CI so the binaries are automatically built when I add a release.
