### ISSUE TITLE
Running for different subdomains deletes all but home

### ISSUE THREAD

**Issue by amirhomayoun** [oscartbeaumont/netlify-dynamic-dns#4]
At the moment, if you run

`./netlify-ddns_linux_amd64 update --domain exmple.com --subdomain "home"`

The correct A types gets created:

```
Name: home.example.com
TTL: 3600 seconds
Type: A
Value: 111.222.333.4444
```

Running again:

`./netlify-ddns_linux_amd64 update --domain exmple.com --subdomain "test"`

Will result in home getting deleted, and having only:

```
Name: test.example.com
TTL: 3600 seconds
Type: A
Value: 111.222.333.444
```

**Comment by oscartbeaumont** [comment]
I am closing this as it should be fixed on the latest version but if it is not I am happy to reopen the issue.
