### ISSUE TITLE
Script unusable due to unresponsive `plausible.otbeaumont.me` subdomain

### ISSUE THREAD

**Issue by junyu33** [oscartbeaumont/netlify-dynamic-dns#69]
Hi, I've been trying to use this script, but it appears to rely on the APIs of your self-hosted subdomain `plausible.otbeaumont.me`. I checked its availability through [isitdownrightnow.com](https://www.isitdownrightnow.com/), and it seems the subdomain isn’t responding, which unfortunately renders the script unusable.  

Could you let us know if there are any plans to address this, or perhaps suggest a workaround for users in the meantime?  

Thanks for your help!

**Comment by trillhc** [comment]
There is an analytics server used in main.go, removing references to it makes it work again.

**Comment by oscartbeaumont** [comment]
Feel free to to PR its removal and I can merge it.

**Comment by junyu33** [comment]
#70 PR added.

**Comment by oscartbeaumont** [comment]
Thanks!
